
author:
    - name: Kel Raphael
      email: raphaelke@vcu.edu

date: last-modified

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

theme: darkly

execute:
  echo: true
  eval: true
  cache: false
