
author:
    - name: Kel Raphael
      email: raphaelke@vcu.edu

date: last-modified

theme: darkly

format:
    html:
        toc: true
        embed-resources: true
        code-copy: true


execute:
  echo: true
  eval: true
  cache: false
